### ISSUE TITLE
Expose JMX MBeans to Prometheus

### ISSUE THREAD

**Issue by mmussett** [TIBCOSoftware/be-tools#137]
Expose the JMX MBeans to Prometheus using the Prometheus JMX Export (https://github.com/prometheus/jmx_exporter) Java Agent so that Prometheus can scrape metrics of the BE Application.

**Comment by vpatil-tibco** [comment]
What is expected here from BE perspective? The way i see it and is being used, different mbeans/object names are relevant for different folks/customers. So they can always use the above github link to do the same via a java agent externally and select the rules for the mbeans/objectnames that are applicable for them.

**Comment by mmussett** [comment]
I don't see any monitoring support provided by the tools as stated on the first page - "The cloud folder provide tools that enables you deploy and monitor". We should expose at least the JVM beans either for scraping or push the attributes to InfluxDB and/or Prometheus for monitoring.

**Comment by vpatil-tibco** [comment]
There are 2 aspects here, the jmx mbeans which monitors internal/system data and then there are user metrics which end users define. For end user metrics we use InfluxDB/LiveView and with upcoming release an option to plug your own.

However, the JMX mbeans can be viewed via any jmx Browser i.e. JConsole/JVisualVM. Now if someone wants to collect internal/system metrics and wants to visualize them via a dashboard. They can surely go ahead and use the prometheus jmx_exporter and pull whatever is relevant for their usecases, since there are ton of jmx beans and attributes. Once they do that, the data will be scrapped for and pushed into prometheus, post which the end user can use any dashboarding tool for visualization i.e. Grafana/etc.
All this can be done even today. So i am not sure, what needs to be added in BE for this?

**Comment by vpatil-tibco** [comment]
Closing the issue. Since all the above can be done event today.
