### ISSUE TITLE
Ability to pull certificates from AWS Certificate Manager during container image build

### ISSUE THREAD

**Issue by mmussett** [TIBCOSoftware/be-tools#165]
**Context**

Ability to pull certificates from AWS Certificate Manager during container image build and to include exported certificates within the container image for consumption by BE Engine.

**Comment by rameshpolishetti** [comment]
Currently user can place certificates into the application folder along with CDD/EAR so that they get copied into the BE container image. I feel, this enhancement request adds little automation to "_pulling certificates from AWS Certificate Manager during BE container image build time_" and covers only this specific case.

To cover more use cases - Make requirement of certificates during build time optional and Add ability to pass certificates during runtime, so that user can reuse the same container image instead of re-creating image just to replace certificates (in case of certificate expiry for example).

Updated enhancement I propose:

"
_Add ability to inject certificates into the BE Engine instance (pod) using Kubernetes Secrets. i.e. Accept certificates as Kubernetes Secrets and mount them into BE pods as files so that they are available inside the running container_
"

@vpatil-tibco please share your view

**Comment by vpatil-tibco** [comment]
Yes that is what we discussed. static/build time makes little sense for this usecase, runtime is more relevant for this. And with kubernetes as our choice of orchestrator, Kubernetes secrets offers the perfect oob solution.

**Comment by LakshmiMekala** [comment]
Design approach:

- Support to Load an existing secret(created using file(s))
- Create a new secret from file(s)
Required volumes and volumemounts to be included in agent templates

**Comment by LakshmiMekala** [comment]
Implemented "Support to Load an existing secret(created using file(s))" and Required volumes and volumemounts to be included in agent templates

**Comment by rameshpolishetti** [comment]
@vilasshelar This can be validated on master branch.

**Comment by tsaxena18** [comment]
I have validated the enhancement on Minikube environment, with single and multiple secrets of type Opaque, having single/multiple certificates. I can see the certificates at the respective location, /opt/tibco/certs/<secretName>.Working fine.

**Comment by rameshpolishetti** [comment]
thank you @tsaxena18
