### ISSUE TITLE
Enable Horizontal Pod Autoscaler functionality 

### ISSUE THREAD

**Issue by rameshpolishetti** [TIBCOSoftware/be-tools#195]
**Context**
Enable Kubernetes native `Horizontal Pod Autoscaler` functionality through BE helm chart, so that the number of `inference` or `cache` pods in the BE deployment gets scaled automatically based on `CPU` and/or `Memory` utilization.

**Alternatives**
It can be done manually.

**Has the feature been requested before?**
NA

**If the feature request is approved, would you be willing to submit a PR?**
Yes

**Comment by LakshmiMekala** [comment]
Feature is made availble in PR #194

**Comment by rameshpolishetti** [comment]
This is made available in PR #213 since the previous PR got dropped.

**Comment by jgirase** [comment]
we have verified hpa for cpu metrics so far using autoscaling example located in minikube folder.We could see inference agent pods scaled up/down as per configuration in values.yaml.

However we are still working on memory metrics and its in progress.
Find logs attached for cpu metrics test for reference.
[HPA_CPU_INF_logs.zip](https://github.com/TIBCOSoftware/be-tools/files/6791663/HPA_CPU_INF_logs.zip)

**Comment by jgirase** [comment]
Tried memory metrics for both cache and inference agents using same autoscaling example. We observed cache and inference pods gets scaled up when data in inserted using readme.html by following mentioned steps in same readme.
However, even after deleting data both pods does not gets scaled down and stays in similar state. 
Waited for some time to notice the difference of memory requirement of pods but it was same as previous state.(Memory not scaling down)

Following are few command outputs for reference, Kindly let us know if this is an expected behaviour.

**Before sending events:**
kubectl get pods
NAME                        READY   STATUS    RESTARTS   AGE
booksapp-cacheagent-0       1/1     Running   0          8m50s
booksapp-cacheagent-1       1/1     Running   0          8m21s
booksapp-cacheagent-2       1/1     Running   0          8m19s
booksapp-inferenceagent-0   1/1     Running   0          8m50s

kubectl get hpa
NAME                      REFERENCE                             TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
booksapp-cacheagent       StatefulSet/booksapp-cacheagent       55%/80%, 1%/80%   1         5         3          3m4s
booksapp-inferenceagent   StatefulSet/booksapp-inferenceagent   56%/80%, 1%/80%   1         5         1          3m5s
   
**After Sending data:**

kubectl get pods
NAME                        READY   STATUS    RESTARTS   AGE
booksapp-cacheagent-0       1/1     Running   0          12m
booksapp-cacheagent-1       1/1     Running   0          12m
booksapp-cacheagent-2       1/1     Running   0          12m
booksapp-cacheagent-3       1/1     Running   0          105s
booksapp-cacheagent-4       1/1     Running   0          59s
booksapp-inferenceagent-0   1/1     Running   0          12m
booksapp-inferenceagent-1   1/1     Running   0          2m15s
booksapp-inferenceagent-2   1/1     Running   0          74s

 kubectl get hpa
NAME                      REFERENCE                             TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
booksapp-cacheagent       StatefulSet/booksapp-cacheagent       89%/80%, 1%/80%   1         5         5          34m
booksapp-inferenceagent   StatefulSet/booksapp-inferenceagent   80%/80%, 1%/80%   1         5         3          34m

**After deleting data/After waiting for some time:**
kubectl get pods
NAME                        READY   STATUS    RESTARTS   AGE
booksapp-cacheagent-0       1/1     Running   0          34m
booksapp-cacheagent-1       1/1     Running   0          34m
booksapp-cacheagent-2       1/1     Running   0          34m
booksapp-cacheagent-3       1/1     Running   0          23m
booksapp-cacheagent-4       1/1     Running   0          22m
booksapp-inferenceagent-0   1/1     Running   0          34m
booksapp-inferenceagent-1   1/1     Running   0          24m
booksapp-inferenceagent-2   1/1     Running   0          23m

kubectl get hpa
NAME                      REFERENCE                             TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
booksapp-cacheagent       StatefulSet/booksapp-cacheagent       89%/80%, 1%/80%   1         5         5          47m
booksapp-inferenceagent   StatefulSet/booksapp-inferenceagent   80%/80%, 1%/80%   1         5         3          47m

 kubectl top pods --sort-by=memory
NAME                        CPU(cores)   MEMORY(bytes)   
booksapp-inferenceagent-0   14m          1266Mi          
booksapp-cacheagent-1       12m          981Mi           
booksapp-cacheagent-2       13m          971Mi           
booksapp-cacheagent-0       14m          960Mi           
booksapp-cacheagent-3       12m          860Mi           
booksapp-cacheagent-4       14m          796Mi           
booksapp-inferenceagent-2   11m          613Mi           
booksapp-inferenceagent-1   13m          593Mi

**Comment by LakshmiMekala** [comment]
@jgirase HPA calculates average of the memory/cpu metrics for specific interval of time. Based on the above mentioned output, pods are utlizing higher memory, so pods are not scaling down. Can you try with a different example which will simulate memory load on cache agent and share the results

**Comment by jgirase** [comment]
@LakshmiMekala this example adds data to cache agents which in turn results in memory grow from around 540Mi to 1.1Gi.
It also scales up pods once it reached to 80% as mentioned in values.yaml. Then there are events to delete data from cache upon which memory should be declined but that is not happening in this case.
For more detailed steps please refer readme.html located under minikube/autoscaling folder

**Comment by LakshmiMekala** [comment]
@jgirase  Agreed, but why the cache agents are utlizing around 950MB of data for each pod?

**Comment by jgirase** [comment]
For more details on how memory is utilised by BE application (cache agent or inference agent) , kindly sync up with our Developers.

**Comment by vpatil-tibco** [comment]
@jgirase - Is this behavior k8 specific or are you seeing this for a simple on-prem(minus docker/k8) usecase? Also does it apply only to AS or to ignite as well?

**Comment by jgirase** [comment]
The behaviour related to cache agent memory does not get released even after deleting data is reproducible on-prem as well specifically on my ubuntu machine. So far the test is run with AS2 only. For ignite we need to repeat the test if required.

**Comment by vpatil-tibco** [comment]
@jgirase - Ok, so this is not related to kubernetes. Create a separate issue in JIRA and assign it to one of the dev team members.

If all things are good from functional perspective around auto scaling, we can close this issue.

**Comment by tsaxena18** [comment]
@vpatil-tibco I can observe the same behavior on other cloud platform and when I tried locally(on-premise without k8) then found a difference in behavior on Win and Linux. The memory usage goes down in Win but not in Linux (Ubuntu & CentOS).
I have created a JIRA and attached my findings.

**Comment by LakshmiMekala** [comment]
Closing as per above comments
