### ISSUE TITLE
Allow complete usage of optimize flag for s2ibuilder based imges.

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#260]
### Version Information
| Software       | Version(s)     |
| -------------- | -------------- |
| BusinessEvents |    6.2.1            |
| OS Type?       |     CentOS           |
| OS Version?    |     7.9           |
| Docker         |     20.10           |
| Kubernetes     |       NA         |
| Helm           |              NA  |

### What is the expected behavior?
While building s2i based image, if we pass optimize flag then the modules should be automtically picked.
./build_image.sh -i s2ibuilder -t s2ibuilder2 -s /home/apps/Installations/BE/BE_621_GA/be/6.2 --optimize http,as2

### What is the actual behavior?
We can pass optimize flag while building s2i based image but we also have to provide modules name as there is no provision for passing EAR/CDD at the same time. Since building application image via s2i based image is a two step process and while creating application image from s2i base image we cannot use flag as it is done by s2i utility so there can be a provision at the time of creating base image only,  to have a uniformity in creating images with or without using s2i.

**Comment by tsaxena18** [comment]
I think if we somehow provide EAR/CDD(optional) to s2i base image with a flag then it will eventually create app image so the next step of building application image from s2i utility (where we are again providing EAR/CDD) should just update the app image with the given CDD/EAR , assuming that there is no change w.r.t modules. But I am not sure whether s2i utility supports that.

**Comment by rameshpolishetti** [comment]
@tsaxena18 I assume that the ask here is to automate user input module names while building `s2ibuilder ` image, which definitely eliminates the pain of entering module names manually. However automating this by accepting CDD/EAR will bring new challenges. To explain in detail - right now user can build BE container image in two ways:
1. build `app` image in a single step by providing CDD/EAR
2. build `s2ibuilder` base image first without providing CDD/EAR and later  build `app` image when CDD/EAR available.

User can choose one of the above options based on, whether the CDD/EAR is available at the time of build OR how frequent CDD/EAR changes so he need to rebuild the image.

With this context, accepting CDD/EAR at the time of `s2ibuilder` image will bring following challenges / more intricate scenarios:
1. Since CDD/EAR is provided, user might expect that resulting image should be a `app` image. Which will oppose the original idea of building `app` image in 2 steps.
2. Scenario (user provided CDD/EAR and available in the `s2ibuilder` image): After building `app` image from builder image by replacing CDD/EAR with new ones, sill old CDD/EAR exists underlaying docker layers. -> unnecessary un used docker image size.
3. Scenario (Use CDD/EAR only to extract module names and then discard CDD/EAR): user experience conflict i.e user can expect a `app` image as he provided CDD/EAR `vs` he could have build `app` image directly as he is having CDD/EAR

Need to brainstorm more on this as it will impact user experience.
