### ISSUE TITLE
TIBCO BusinessEvents (BE) should support custom config management in addition to Consul

### ISSUE THREAD

**Issue by p-admabhushan** [TIBCOSoftware/be-tools#64]
TIBCO BusinessEvents (BE) should support custom config management in addition to Consul something like BWCE (https://github.com/TIBCOSoftware/bw-samples/wiki/Custom-Config-Management)

**Comment by vpatil-tibco** [comment]
Since the example above is reference only and a thick client studio based support, it does not align with what we have. Below are the details of how we plan to support this,

1. Plugin based support. End user should be able to plugin support for pulling data from whatever end store they maintain their configurations. If that means FTL needs to be used to retrieve the details, then the end user will provide the implementation to retrieve the contents using FTL and pass it on to the framework. 

2. OOB support for HTTP based config. E.g. if the end user has it stores at server/store/etc, but has an http based api to access it, then he/she can leverage this config type. Some of the cloud resources like AWS S2, Azure Blob, do have http based API's available. So they might too be able to leverage this.

3. Existing Consul support to be updated to align this plugin framework.

**Comment by rameshpolishetti** [comment]
This enhancement is available at https://github.com/TIBCOSoftware/be-tools/tree/docker-scripts-improvements/cloud/docker/gvproviders

**Comment by ykalidin** [comment]
Checked with aws custom config. Working as expected. Consul is aligned with the new framework.

**Comment by jgirase** [comment]
Verified consul gv provider on EKS. Find attached logs for reference. 
[consul_logs.zip](https://github.com/TIBCOSoftware/be-tools/files/5715892/consul_logs.zip)

**Comment by rameshpolishetti** [comment]
Thank you @jgirase. Closing the issue as it is verified successfully.

**Comment by rameshpolishetti** [comment]
This enhancement got merged into master. Please refer to the  documentation at https://github.com/TIBCOSoftware/be-tools/wiki/Using-GV-Configuration-Framework
